// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Pay.Service.Wallets.Client.Models
{
    using Lykke.Pay;
    using Lykke.Pay.Service;
    using Lykke.Pay.Service.Wallets;
    using Lykke.Pay.Service.Wallets.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Wallet
    {
        /// <summary>
        /// Initializes a new instance of the Wallet class.
        /// </summary>
        public Wallet()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Wallet class.
        /// </summary>
        public Wallet(string walletAddress = default(string))
        {
            WalletAddress = walletAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WalletAddress")]
        public string WalletAddress { get; set; }

    }
}
